### ISSUE TITLE
Acceso a la imagen

### ISSUE THREAD

**Issue by GabrielCarbia** [pdepviernestm/2023-bienvenida-sofitofischer#1]
Buenas, fijate el tema del acceso a la imagen porque no se puede ver en la presentación. (directamente arrastrando de la carpeta hacia el código se copiara el link para que pueda verse la imagen y no un enlace), a mi me paso lo mismo 🤪

**Comment by sofitofischer** [comment]
Holaa, muchas gracias! A mí me aparecía la imagen, pero parece que solo yo la podía ver. Ahí hice lo que me dijiste, espero que ahora sí se vea
