### ISSUE TITLE
Agregar provincia en donde vives

### ISSUE THREAD

**Issue by Dummatt** [pdepviernestm/2023-bienvenida-sofitofischer#4]
Si bien se puede deducir esto por tu escuela, es igual posible que te hayas mudado a otro lado. Así que sería genial saber si vives en ciudad o provincia de buenos aires, o hasta en otro lado, quien sabe. Estudiantes hay en todos lados :P

**Comment by sofitofischer** [comment]
Hola! Tenés razón jajaj, gracias, ahora lo agrego
